# Generated by Django 5.0.6 on 2024-05-18 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Besin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('protein', models.DecimalField(decimal_places=5, max_digits=10)),
                ('yağ', models.DecimalField(decimal_places=5, max_digits=10)),
                ('karbonhidrat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('gram', models.DecimalField(decimal_places=5, max_digits=10)),
                ('kalori', models.DecimalField(decimal_places=5, max_digits=10)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besinler', to='kategori.kategori')),
            ],
        ),
    ]
